#!/usr/bin/env python

# Takes an IATI XML file on stdin; outputs CSV of data relevant to the budget

import sys
import lxml.etree
import csv

def tuple_of_elt(elt):
    def by_name(name): return elt.find(name).text

    title           = by_name("title")
    reporting_org   = by_name("reporting-org")
    iati_identifier = by_name("iati-identifier")
    sector          = by_name("sector")
    sector_code     = elt.find("sector").attrib['code']

    def get_dates():
        activity_dates = elt.findall('activity-date')
        for ad in activity_dates:
            ty = ad.attrib['type']
            iso_date = ad.attrib['iso-date']
            yield (ty, iso_date)
    
    activity_dates = dict(get_dates())

    start_actual    = activity_dates["start-actual"]
    start_planned   = activity_dates["start-planned"]
    end_actual      = activity_dates["end-actual"]
    end_planned     = activity_dates["end-planned"]
    recipient_cntry = by_name('recipient-country')
    rec_code        = elt.find('recipient-country').attrib['code']

    return (
        title,
        reporting_org,
        iati_identifier,
        sector_code,
        sector,
        start_actual,
        end_actual,
        recipient_cntry,
        rec_code
        )

def run():
    root = lxml.etree.parse(sys.stdin)

    w = csv.writer(sys.stdout)

    for elt in root.xpath('//iati-activity'):
        row = tuple_of_elt(elt)
        w.writerow(row)
        
if __name__ == '__main__':
    run()
